// <auto-generated />
using System;
using ApiClientes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace api_project_net5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240730234944_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ApiClientes.Data.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "12345678901234",
                            DataCadastro = new DateTime(2024, 7, 30, 20, 49, 44, 559, DateTimeKind.Local).AddTicks(5717),
                            Endereco = "Rua 1, 123",
                            Nome = "Empresa 1",
                            Telefone = "5548912345678"
                        },
                        new
                        {
                            Id = 2,
                            CNPJ = "43210987654321",
                            DataCadastro = new DateTime(2024, 7, 30, 20, 49, 44, 560, DateTimeKind.Local).AddTicks(2066),
                            Endereco = "Rua 2, 123",
                            Nome = "Empresa 2",
                            Telefone = "5548987654321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
