// <auto-generated />
using System;
using Clientes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace api_project_net5.Migrations
{
    [DbContext(typeof(ClientesDbContext))]
    [Migration("20240731022806_CreateClientesSchema")]
    partial class CreateClientesSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Clientes.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasCheckConstraint("CK_CNPJ_Length", "LENGTH(\"CNPJ\") = 14");

                    b.HasCheckConstraint("CK_Telefone_Length", "LENGTH(\"Telefone\") = 13");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "12345678901234",
                            DataCadastro = new DateTime(2024, 7, 30, 23, 28, 6, 375, DateTimeKind.Local).AddTicks(8915),
                            Endereco = "Rua 1, 123",
                            Nome = "Empresa 1",
                            Telefone = "5548912345678"
                        },
                        new
                        {
                            Id = 2,
                            CNPJ = "43210987654321",
                            DataCadastro = new DateTime(2024, 7, 30, 23, 28, 6, 376, DateTimeKind.Local).AddTicks(4976),
                            Endereco = "Rua 2, 123",
                            Nome = "Empresa 2",
                            Telefone = "5548987654321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
